export { StarmapRenderer } from './renderer/StarmapRenderer.js'
export type { StarmapRendererOptions, HoverHandler } from './renderer/StarmapRenderer.js'
export { heatmapLayer } from './layers/heatmapLayer.js'
export type { HeatmapLayerOptions } from './layers/heatmapLayer.js'
export { regionLabelLayer } from './layers/regionLabelLayer.js'
export type { RegionLabelLayerOptions } from './layers/regionLabelLayer.js'
export { validateUniverseData } from './dataValidation.js'
export { createColorScale } from './colorScale.js'
export type { ColorScaleOptions } from './colorScale.js'
export { defaultUniverseData } from './data/defaultUniverseData.js'
export { excludeRegions, POCHVEN_REGION_ID } from './regionFilter.js'
export { SYSTEM_DOT_RADIUS } from './constants.js'
export type { UniverseData, SystemNode, StargateEdge, RegionNode, Layer, Viewport } from './types.js'
